[package]
name = "asteroids"
version = "0.1.0"
authors = ["Matthew Blake"]
edition = "2018"

[dependencies]
amethyst = { version = "0.13.2", features = ["nightly"] }

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
